/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsercardRouteImport } from './routes/usercard'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as LorebooksRouteImport } from './routes/lorebooks'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as IndexRouteImport } from './routes/index'

const UsercardRoute = UsercardRouteImport.update({
  id: '/usercard',
  path: '/usercard',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LorebooksRoute = LorebooksRouteImport.update({
  id: '/lorebooks',
  path: '/lorebooks',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/lorebooks': typeof LorebooksRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/usercard': typeof UsercardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/lorebooks': typeof LorebooksRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/usercard': typeof UsercardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/lorebooks': typeof LorebooksRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/usercard': typeof UsercardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor' | '/lorebooks' | '/oauth-callback' | '/usercard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/lorebooks' | '/oauth-callback' | '/usercard'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/lorebooks'
    | '/oauth-callback'
    | '/usercard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  LorebooksRoute: typeof LorebooksRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  UsercardRoute: typeof UsercardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usercard': {
      id: '/usercard'
      path: '/usercard'
      fullPath: '/usercard'
      preLoaderRoute: typeof UsercardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lorebooks': {
      id: '/lorebooks'
      path: '/lorebooks'
      fullPath: '/lorebooks'
      preLoaderRoute: typeof LorebooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  LorebooksRoute: LorebooksRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  UsercardRoute: UsercardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
